=== Romainlbss/RomainFleurySite/XML/Catalogue.dtd
<!ELEMENT catalogue (figurine+)>

<!ELEMENT figurine (nom, theme, description, caracteristiques, prix, photos)>
<!ATTLIST figurine 
    id ID #REQUIRED>

<!ELEMENT nom (#PCDATA)>

<!ELEMENT theme (#PCDATA)>
<!ATTLIST theme 
    categorie (StarWars|HarryPotter|Ninjago|Simpson|DCComics|Aucune) "Aucune">

<!ELEMENT description (#PCDATA)>

<!ELEMENT caracteristiques (sortie, nombre_de_pieces)>

<!ELEMENT sortie (#PCDATA)>

<!ELEMENT nombre_de_pieces (#PCDATA)>
<!ATTLIST nombre_de_pieces 
    nombre CDATA #REQUIRED>

<!ELEMENT photos (#PCDATA)>
<!ATTLIST photos
    chemin CDATA #REQUIRED
    lien CDATA #REQUIRED>


<!ELEMENT prix (#PCDATA)>
<!ATTLIST prix
    prix CDATA #REQUIRED>

=== Romainlbss/RomainFleurySite/XML/Fiches.xml
<?xml version="1.0" ?>
<!DOCTYPE catalogue SYSTEM "Catalogue.dtd">
<catalogue>
    <figurine id="fig001">
        <nom>Sensei Wu</nom>
        <theme categorie="Ninjago"></theme>
        <description>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
            magna aliqua. Porttitor leo a diam sollicitudin. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel. 
            Urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Posuere ac ut consequat semper viverra. 
            Viverra nam libero justo laoreet sit. Auctor neque vitae tempus quam pellentesque nec nam aliquam. 
            Nunc consequat interdum varius sit amet mattis. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. 
            Nisl nunc mi ipsum faucibus vitae aliquet. Lobortis mattis aliquam faucibus purus in massa. Urna duis convallis 
            convallis tellus id interdum velit laoreet. Diam phasellus vestibulum lorem sed risus. Id velit ut tortor pretium 
            viverra suspendisse potenti nullam. A diam sollicitudin tempor id eu nisl nunc.
        </description>
        <caracteristiques>
            <sortie>2019</sortie>
            <nombre_de_pieces nombre="6"></nombre_de_pieces>
        </caracteristiques>
        <prix prix="5,99€"></prix>
        <photos chemin="/Images/minifigure-lego-ninjago-sensei-wu-legacy.jpg" lien="http://127.0.0.1:5500/Content/Collection/fig001.xhtml"></photos>
    </figurine>
    <figurine id="fig002">
        <nom>Luke Skywalker</nom>
        <theme categorie="StarWars"></theme>
        <description>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
            magna aliqua. Porttitor leo a diam sollicitudin. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel. 
            Urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Posuere ac ut consequat semper viverra. 
            Viverra nam libero justo laoreet sit. Auctor neque vitae tempus quam pellentesque nec nam aliquam. 
            Nunc consequat interdum varius sit amet mattis. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. 
            Nisl nunc mi ipsum faucibus vitae aliquet. Lobortis mattis aliquam faucibus purus in massa. Urna duis convallis 
            convallis tellus id interdum velit laoreet. Diam phasellus vestibulum lorem sed risus. Id velit ut tortor pretium 
            viverra suspendisse potenti nullam. A diam sollicitudin tempor id eu nisl nunc.
        </description>
        <caracteristiques>
            <sortie>2022</sortie>
            <nombre_de_pieces nombre="4"></nombre_de_pieces>
        </caracteristiques>
        <prix prix="9,99€"></prix>
        <photos chemin="/Images/minifigure-lego-star-wars-luke-skywalker-cloud-city.jpg" lien="http://127.0.0.1:5500/Content/Collection/fig002.xhtml"></photos>
    </figurine>
    <figurine id="fig003">
        <nom>Harry Potter</nom>
        <theme categorie="HarryPotter"></theme>
        <description>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
            magna aliqua. Porttitor leo a diam sollicitudin. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel. 
            Urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Posuere ac ut consequat semper viverra. 
            Viverra nam libero justo laoreet sit. Auctor neque vitae tempus quam pellentesque nec nam aliquam. 
            Nunc consequat interdum varius sit amet mattis. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. 
            Nisl nunc mi ipsum faucibus vitae aliquet. Lobortis mattis aliquam faucibus purus in massa. Urna duis convallis 
            convallis tellus id interdum velit laoreet. Diam phasellus vestibulum lorem sed risus. Id velit ut tortor pretium 
            viverra suspendisse potenti nullam. A diam sollicitudin tempor id eu nisl nunc.
        </description>
        <caracteristiques>
            <sortie>2019</sortie>
            <nombre_de_pieces nombre="4"></nombre_de_pieces>
        </caracteristiques>
        <prix prix="6,66€"></prix>
        <photos chemin="/Images/harry_potter_lego.jpg" lien="http://127.0.0.1:5500/Content/Collection/fig003.xhtml"></photos>
    </figurine>
    <figurine id="fig004">
        <nom>Bart</nom>
        <theme categorie="Simpson"></theme>
        <description>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
            magna aliqua. Porttitor leo a diam sollicitudin. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel. 
            Urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Posuere ac ut consequat semper viverra. 
            Viverra nam libero justo laoreet sit. Auctor neque vitae tempus quam pellentesque nec nam aliquam. 
            Nunc consequat interdum varius sit amet mattis. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. 
            Nisl nunc mi ipsum faucibus vitae aliquet. Lobortis mattis aliquam faucibus purus in massa. Urna duis convallis 
            convallis tellus id interdum velit laoreet. Diam phasellus vestibulum lorem sed risus. Id velit ut tortor pretium 
            viverra suspendisse potenti nullam. A diam sollicitudin tempor id eu nisl nunc.
        </description>
        <caracteristiques>
            <sortie>2015</sortie>
            <nombre_de_pieces nombre="5"></nombre_de_pieces>
        </caracteristiques>
        <prix prix="8,99€"></prix>
        <photos chemin="/Images/minifigure-lego-simpson-serie-2-bart.jpg" lien="http://127.0.0.1:5500/Content/Collection/fig004.xhtml"></photos>
    </figurine>
    <figurine id="fig005">
        <nom>Lisa</nom>
        <theme categorie="Simpson"></theme>
        <description>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
            magna aliqua. Porttitor leo a diam sollicitudin. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel. 
            Urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Posuere ac ut consequat semper viverra. 
            Viverra nam libero justo laoreet sit. Auctor neque vitae tempus quam pellentesque nec nam aliquam. 
            Nunc consequat interdum varius sit amet mattis. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. 
            Nisl nunc mi ipsum faucibus vitae aliquet. Lobortis mattis aliquam faucibus purus in massa. Urna duis convallis 
            convallis tellus id interdum velit laoreet. Diam phasellus vestibulum lorem sed risus. Id velit ut tortor pretium 
            viverra suspendisse potenti nullam. A diam sollicitudin tempor id eu nisl nunc.
        </description>
        <caracteristiques>
            <sortie>2015</sortie>
            <nombre_de_pieces nombre="4"></nombre_de_pieces>
        </caracteristiques>
        <prix prix="9,99€"></prix>
        <photos chemin="/Images/minifigure_lego_lisa.jpg" lien="http://127.0.0.1:5500/Content/Collection/fig005.xhtml"></photos>
    </figurine>
    <figurine id="fig006">
        <nom>Le Joker</nom>
        <theme categorie="DCComics"></theme>
        <description>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
            magna aliqua. Porttitor leo a diam sollicitudin. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel. 
            Urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Posuere ac ut consequat semper viverra. 
            Viverra nam libero justo laoreet sit. Auctor neque vitae tempus quam pellentesque nec nam aliquam.
        </description>
        <caracteristiques>
            <sortie>2020</sortie>
            <nombre_de_pieces nombre="6"></nombre_de_pieces>
        </caracteristiques>
        <prix prix="9,99€"></prix>
        <photos chemin="/Images/minifigure-lego-dc-comics-le-joker.jpg" lien="http://127.0.0.1:5500/Content/Collection/fig006.xhtml"></photos>
    </figurine>
    <figurine id="fig007">
        <nom>Miles Morales</nom>
        <theme categorie="Marvel"></theme>
        <description>
            Miles Morales est un jeune garçon de 13 ans (bientôt 14 !) qui a des pouvoirs similaires à Spider-Man. Miles vit dans un univers alternatif où le Spider-Man original a sacrifié sa vie pour sauver la planète. Fort de ses nouveaux pouvoirs d'homme-araignée et prenant Peter Parker comme modèle, il a revêtu le costume de Spider-Man pour démontrer qu'un grand pouvoir impliquait de grandes responsabilités.
        </description>
        <caracteristiques>
            <sortie>2023</sortie>
            <nombre_de_pieces nombre="3"></nombre_de_pieces>
        </caracteristiques>
        <prix prix="9,99€"></prix>
        <photos chemin="/Images/minifigure-lego-marvel-spider-man-miles-morales.jpg" lien="http://127.0.0.1:5500/Content/Collection/fig007.xhtml"></photos>
    </figurine>
    <figurine id="fig008">
        <nom>Tony Stark</nom>
        <theme categorie="Marvel"></theme>
        <description>
            Dans son armure tactique d'Iron Man, Tony Stark peut presque tout faire : survoler les océans, tirer des rayons répulseurs, et lutter contre les super criminels et les invasions extraterrestres. Mais même hors de son armure high-tech, le milliardaire est une force redoutable, en raison de son génie et de son imagination inventive.
        </description>
        <caracteristiques>
            <sortie>2020</sortie>
            <nombre_de_pieces nombre="4"></nombre_de_pieces>
        </caracteristiques>
        <prix prix="7,99€"></prix>
        <photos chemin="/Images/TonyStark.jpg" lien="http://127.0.0.1:5500/Content/Collection/fig008.xhtml"></photos>
    </figurine>
    <figurine id="fig009">
        <nom>Hulk</nom>
